import { useContext } from "react";
import Head from "next/head";
import { Inter } from "@next/font/google";
import styles from "../styles/Home.module.css";
import MainBanner from "../components/MainBanner/MainBanner";
import { Container, Box, Typography, Button } from "@mui/material";
import Plans from "../components/Plans/Plans";
import { AuthContext } from "../contexts/authContext";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const { user } = useContext(AuthContext);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Container>
          <Box my={8}>
            <MainBanner />
          </Box>
          <Box
            my={8}
            sx={{ display: "flex", alignItems: "center", gap: "20px" }}
          >
            <iframe
              width="560"
              height="315"
              src="https://www.youtube.com/embed/1rVWb7YivNk"
              title="YouTube video player"
              frameborder="0"
              allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
              allowfullscreen
            ></iframe>
            <Box>
              <Typography variant="h4"> Learn About Surebets</Typography>
              <Typography>
                A complete video explaining how it works behind the scenes.
              </Typography>
            </Box>
          </Box>
          {!(user?.status == "active") && (
            <Box my={8}>
              <Plans />
            </Box>
          )}
        </Container>
      </main>
    </>
  );
}
